// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package db

import (
	"context"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (email_id, filename, content_type, size, storage_path, created_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, email_id, filename, content_type, size, storage_path, created_at
`

type CreateAttachmentParams struct {
	EmailID     int64  `json:"email_id"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	Size        int64  `json:"size"`
	StoragePath string `json:"storage_path"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, createAttachment,
		arg.EmailID,
		arg.Filename,
		arg.ContentType,
		arg.Size,
		arg.StoragePath,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.EmailID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = ?
`

func (q *Queries) DeleteAttachment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAttachment, id)
	return err
}

const deleteAttachmentsByEmail = `-- name: DeleteAttachmentsByEmail :exec
DELETE FROM attachments WHERE email_id = ?
`

func (q *Queries) DeleteAttachmentsByEmail(ctx context.Context, emailID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAttachmentsByEmail, emailID)
	return err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, email_id, filename, content_type, size, storage_path, created_at FROM attachments WHERE id = ? LIMIT 1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id int64) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.EmailID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByEmail = `-- name: ListAttachmentsByEmail :many
SELECT id, email_id, filename, content_type, size, storage_path, created_at FROM attachments WHERE email_id = ? ORDER BY id
`

func (q *Queries) ListAttachmentsByEmail(ctx context.Context, emailID int64) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByEmail, emailID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.EmailID,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.StoragePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
