// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domains.sql

package db

import (
	"context"
)

const countDomains = `-- name: CountDomains :one
SELECT COUNT(*) FROM domains
`

func (q *Queries) CountDomains(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDomains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (name, is_verified, is_active)
VALUES (?, ?, ?)
RETURNING id, name, is_verified, is_active, created_at, updated_at
`

type CreateDomainParams struct {
	Name       string `json:"name"`
	IsVerified int64  `json:"is_verified"`
	IsActive   int64  `json:"is_active"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, createDomain, arg.Name, arg.IsVerified, arg.IsActive)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains WHERE id = ?
`

func (q *Queries) DeleteDomain(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDomain, id)
	return err
}

const domainExistsByName = `-- name: DomainExistsByName :one
SELECT COUNT(*) FROM domains WHERE name = ?
`

func (q *Queries) DomainExistsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, domainExistsByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDomainByID = `-- name: GetDomainByID :one
SELECT id, name, is_verified, is_active, created_at, updated_at FROM domains WHERE id = ?
`

func (q *Queries) GetDomainByID(ctx context.Context, id int64) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getDomainByID, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainByName = `-- name: GetDomainByName :one
SELECT id, name, is_verified, is_active, created_at, updated_at FROM domains WHERE name = ?
`

func (q *Queries) GetDomainByName(ctx context.Context, name string) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getDomainByName, name)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDomains = `-- name: ListActiveDomains :many
SELECT id, name, is_verified, is_active, created_at, updated_at FROM domains WHERE is_active = 1 ORDER BY name ASC
`

func (q *Queries) ListActiveDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsVerified,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomains = `-- name: ListDomains :many
SELECT id, name, is_verified, is_active, created_at, updated_at FROM domains ORDER BY name ASC
`

func (q *Queries) ListDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, listDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsVerified,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDomain = `-- name: UpdateDomain :one
UPDATE domains
SET name = ?, is_verified = ?, is_active = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, is_verified, is_active, created_at, updated_at
`

type UpdateDomainParams struct {
	Name       string `json:"name"`
	IsVerified int64  `json:"is_verified"`
	IsActive   int64  `json:"is_active"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateDomain(ctx context.Context, arg UpdateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, updateDomain,
		arg.Name,
		arg.IsVerified,
		arg.IsActive,
		arg.ID,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
