// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mailboxes.sql

package db

import (
	"context"
	"database/sql"
)

const countMailboxes = `-- name: CountMailboxes :one
SELECT COUNT(*) FROM mailboxes
`

func (q *Queries) CountMailboxes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMailboxes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMailbox = `-- name: CreateMailbox :one
INSERT INTO mailboxes (slug, owner_id, domain_id, description, is_active, max_email_size_mb, max_attachment_size_mb, retention_days, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, slug, owner_id, description, is_active, created_at, updated_at, domain_id, max_email_size_mb, max_attachment_size_mb, retention_days
`

type CreateMailboxParams struct {
	Slug                string         `json:"slug"`
	OwnerID             sql.NullInt64  `json:"owner_id"`
	DomainID            sql.NullInt64  `json:"domain_id"`
	Description         sql.NullString `json:"description"`
	IsActive            int64          `json:"is_active"`
	MaxEmailSizeMb      int64          `json:"max_email_size_mb"`
	MaxAttachmentSizeMb int64          `json:"max_attachment_size_mb"`
	RetentionDays       int64          `json:"retention_days"`
}

func (q *Queries) CreateMailbox(ctx context.Context, arg CreateMailboxParams) (Mailbox, error) {
	row := q.db.QueryRowContext(ctx, createMailbox,
		arg.Slug,
		arg.OwnerID,
		arg.DomainID,
		arg.Description,
		arg.IsActive,
		arg.MaxEmailSizeMb,
		arg.MaxAttachmentSizeMb,
		arg.RetentionDays,
	)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerID,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainID,
		&i.MaxEmailSizeMb,
		&i.MaxAttachmentSizeMb,
		&i.RetentionDays,
	)
	return i, err
}

const deleteMailbox = `-- name: DeleteMailbox :exec
DELETE FROM mailboxes WHERE id = ?
`

func (q *Queries) DeleteMailbox(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMailbox, id)
	return err
}

const getMailboxByID = `-- name: GetMailboxByID :one
SELECT id, slug, owner_id, description, is_active, created_at, updated_at, domain_id, max_email_size_mb, max_attachment_size_mb, retention_days FROM mailboxes WHERE id = ? LIMIT 1
`

func (q *Queries) GetMailboxByID(ctx context.Context, id int64) (Mailbox, error) {
	row := q.db.QueryRowContext(ctx, getMailboxByID, id)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerID,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainID,
		&i.MaxEmailSizeMb,
		&i.MaxAttachmentSizeMb,
		&i.RetentionDays,
	)
	return i, err
}

const getMailboxBySlug = `-- name: GetMailboxBySlug :one
SELECT id, slug, owner_id, description, is_active, created_at, updated_at, domain_id, max_email_size_mb, max_attachment_size_mb, retention_days FROM mailboxes WHERE slug = ? LIMIT 1
`

func (q *Queries) GetMailboxBySlug(ctx context.Context, slug string) (Mailbox, error) {
	row := q.db.QueryRowContext(ctx, getMailboxBySlug, slug)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerID,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainID,
		&i.MaxEmailSizeMb,
		&i.MaxAttachmentSizeMb,
		&i.RetentionDays,
	)
	return i, err
}

const getMailboxBySlugAndDomain = `-- name: GetMailboxBySlugAndDomain :one
SELECT id, slug, owner_id, description, is_active, created_at, updated_at, domain_id, max_email_size_mb, max_attachment_size_mb, retention_days FROM mailboxes WHERE slug = ? AND domain_id = ? LIMIT 1
`

type GetMailboxBySlugAndDomainParams struct {
	Slug     string        `json:"slug"`
	DomainID sql.NullInt64 `json:"domain_id"`
}

func (q *Queries) GetMailboxBySlugAndDomain(ctx context.Context, arg GetMailboxBySlugAndDomainParams) (Mailbox, error) {
	row := q.db.QueryRowContext(ctx, getMailboxBySlugAndDomain, arg.Slug, arg.DomainID)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerID,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainID,
		&i.MaxEmailSizeMb,
		&i.MaxAttachmentSizeMb,
		&i.RetentionDays,
	)
	return i, err
}

const listMailboxes = `-- name: ListMailboxes :many
SELECT id, slug, owner_id, description, is_active, created_at, updated_at, domain_id, max_email_size_mb, max_attachment_size_mb, retention_days FROM mailboxes ORDER BY created_at DESC
`

func (q *Queries) ListMailboxes(ctx context.Context) ([]Mailbox, error) {
	rows, err := q.db.QueryContext(ctx, listMailboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mailbox{}
	for rows.Next() {
		var i Mailbox
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.OwnerID,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DomainID,
			&i.MaxEmailSizeMb,
			&i.MaxAttachmentSizeMb,
			&i.RetentionDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailboxesByDomain = `-- name: ListMailboxesByDomain :many
SELECT id, slug, owner_id, description, is_active, created_at, updated_at, domain_id, max_email_size_mb, max_attachment_size_mb, retention_days FROM mailboxes WHERE domain_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListMailboxesByDomain(ctx context.Context, domainID sql.NullInt64) ([]Mailbox, error) {
	rows, err := q.db.QueryContext(ctx, listMailboxesByDomain, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mailbox{}
	for rows.Next() {
		var i Mailbox
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.OwnerID,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DomainID,
			&i.MaxEmailSizeMb,
			&i.MaxAttachmentSizeMb,
			&i.RetentionDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailboxesByOwner = `-- name: ListMailboxesByOwner :many
SELECT id, slug, owner_id, description, is_active, created_at, updated_at, domain_id, max_email_size_mb, max_attachment_size_mb, retention_days FROM mailboxes WHERE owner_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListMailboxesByOwner(ctx context.Context, ownerID sql.NullInt64) ([]Mailbox, error) {
	rows, err := q.db.QueryContext(ctx, listMailboxesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mailbox{}
	for rows.Next() {
		var i Mailbox
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.OwnerID,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DomainID,
			&i.MaxEmailSizeMb,
			&i.MaxAttachmentSizeMb,
			&i.RetentionDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailboxExistsBySlug = `-- name: MailboxExistsBySlug :one
SELECT EXISTS(SELECT 1 FROM mailboxes WHERE slug = ? AND is_active = 1)
`

func (q *Queries) MailboxExistsBySlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, mailboxExistsBySlug, slug)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const mailboxExistsBySlugAndDomain = `-- name: MailboxExistsBySlugAndDomain :one
SELECT EXISTS(SELECT 1 FROM mailboxes WHERE slug = ? AND domain_id = ? AND is_active = 1)
`

type MailboxExistsBySlugAndDomainParams struct {
	Slug     string        `json:"slug"`
	DomainID sql.NullInt64 `json:"domain_id"`
}

func (q *Queries) MailboxExistsBySlugAndDomain(ctx context.Context, arg MailboxExistsBySlugAndDomainParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, mailboxExistsBySlugAndDomain, arg.Slug, arg.DomainID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateMailbox = `-- name: UpdateMailbox :one
UPDATE mailboxes
SET slug = ?, owner_id = ?, domain_id = ?, description = ?, is_active = ?,
    max_email_size_mb = ?, max_attachment_size_mb = ?, retention_days = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, slug, owner_id, description, is_active, created_at, updated_at, domain_id, max_email_size_mb, max_attachment_size_mb, retention_days
`

type UpdateMailboxParams struct {
	Slug                string         `json:"slug"`
	OwnerID             sql.NullInt64  `json:"owner_id"`
	DomainID            sql.NullInt64  `json:"domain_id"`
	Description         sql.NullString `json:"description"`
	IsActive            int64          `json:"is_active"`
	MaxEmailSizeMb      int64          `json:"max_email_size_mb"`
	MaxAttachmentSizeMb int64          `json:"max_attachment_size_mb"`
	RetentionDays       int64          `json:"retention_days"`
	ID                  int64          `json:"id"`
}

func (q *Queries) UpdateMailbox(ctx context.Context, arg UpdateMailboxParams) (Mailbox, error) {
	row := q.db.QueryRowContext(ctx, updateMailbox,
		arg.Slug,
		arg.OwnerID,
		arg.DomainID,
		arg.Description,
		arg.IsActive,
		arg.MaxEmailSizeMb,
		arg.MaxAttachmentSizeMb,
		arg.RetentionDays,
		arg.ID,
	)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerID,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainID,
		&i.MaxEmailSizeMb,
		&i.MaxAttachmentSizeMb,
		&i.RetentionDays,
	)
	return i, err
}
