// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Attachment struct {
	ID          int64     `json:"id"`
	EmailID     int64     `json:"email_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	Size        int64     `json:"size"`
	StoragePath string    `json:"storage_path"`
	CreatedAt   time.Time `json:"created_at"`
}

type Domain struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	IsVerified int64     `json:"is_verified"`
	IsActive   int64     `json:"is_active"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type DomainTag struct {
	DomainID int64 `json:"domain_id"`
	TagID    int64 `json:"tag_id"`
}

type Email struct {
	ID          int64          `json:"id"`
	MailboxID   int64          `json:"mailbox_id"`
	MessageID   sql.NullString `json:"message_id"`
	FromAddress string         `json:"from_address"`
	ToAddress   string         `json:"to_address"`
	Subject     sql.NullString `json:"subject"`
	Date        sql.NullString `json:"date"`
	Headers     sql.NullString `json:"headers"`
	TextBody    sql.NullString `json:"text_body"`
	HtmlBody    sql.NullString `json:"html_body"`
	RawSize     int64          `json:"raw_size"`
	ReceivedAt  time.Time      `json:"received_at"`
}

type Mailbox struct {
	ID                  int64          `json:"id"`
	Slug                string         `json:"slug"`
	OwnerID             sql.NullInt64  `json:"owner_id"`
	Description         sql.NullString `json:"description"`
	IsActive            int64          `json:"is_active"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DomainID            sql.NullInt64  `json:"domain_id"`
	MaxEmailSizeMb      int64          `json:"max_email_size_mb"`
	MaxAttachmentSizeMb int64          `json:"max_attachment_size_mb"`
	RetentionDays       int64          `json:"retention_days"`
}

type MailboxTag struct {
	MailboxID int64 `json:"mailbox_id"`
	TagID     int64 `json:"tag_id"`
}

type Session struct {
	ID        int64     `json:"id"`
	Token     string    `json:"token"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Setting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Tag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID              int64          `json:"id"`
	Email           string         `json:"email"`
	PasswordHash    string         `json:"password_hash"`
	IsAdmin         int64          `json:"is_admin"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	AvatarPath      sql.NullString `json:"avatar_path"`
	FirstName       sql.NullString `json:"first_name"`
	LastName        sql.NullString `json:"last_name"`
	TotpSecret      sql.NullString `json:"totp_secret"`
	TotpEnabled     int64          `json:"totp_enabled"`
	TotpBackupCodes sql.NullString `json:"totp_backup_codes"`
}

type Webhook struct {
	ID                 int64          `json:"id"`
	MailboxID          int64          `json:"mailbox_id"`
	Name               string         `json:"name"`
	Url                string         `json:"url"`
	Headers            sql.NullString `json:"headers"`
	HmacSecret         sql.NullString `json:"hmac_secret"`
	TimeoutSec         int64          `json:"timeout_sec"`
	MaxRetries         int64          `json:"max_retries"`
	IncludeBody        int64          `json:"include_body"`
	IncludeAttachments int64          `json:"include_attachments"`
	IsActive           int64          `json:"is_active"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type WebhookDelivery struct {
	ID           int64          `json:"id"`
	WebhookID    int64          `json:"webhook_id"`
	EmailID      int64          `json:"email_id"`
	Attempt      int64          `json:"attempt"`
	Status       string         `json:"status"`
	StatusCode   sql.NullInt64  `json:"status_code"`
	RequestBody  sql.NullString `json:"request_body"`
	ResponseBody sql.NullString `json:"response_body"`
	ErrorMessage sql.NullString `json:"error_message"`
	DurationMs   sql.NullInt64  `json:"duration_ms"`
	CreatedAt    time.Time      `json:"created_at"`
}

type WebhookRule struct {
	ID         int64          `json:"id"`
	WebhookID  int64          `json:"webhook_id"`
	RuleGroup  int64          `json:"rule_group"`
	Field      string         `json:"field"`
	Operator   string         `json:"operator"`
	Value      string         `json:"value"`
	HeaderName sql.NullString `json:"header_name"`
	CreatedAt  time.Time      `json:"created_at"`
}
