// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"
)

const addTagToDomain = `-- name: AddTagToDomain :exec
INSERT OR IGNORE INTO domain_tags (domain_id, tag_id) VALUES (?, ?)
`

type AddTagToDomainParams struct {
	DomainID int64 `json:"domain_id"`
	TagID    int64 `json:"tag_id"`
}

func (q *Queries) AddTagToDomain(ctx context.Context, arg AddTagToDomainParams) error {
	_, err := q.db.ExecContext(ctx, addTagToDomain, arg.DomainID, arg.TagID)
	return err
}

const addTagToMailbox = `-- name: AddTagToMailbox :exec
INSERT OR IGNORE INTO mailbox_tags (mailbox_id, tag_id) VALUES (?, ?)
`

type AddTagToMailboxParams struct {
	MailboxID int64 `json:"mailbox_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) AddTagToMailbox(ctx context.Context, arg AddTagToMailboxParams) error {
	_, err := q.db.ExecContext(ctx, addTagToMailbox, arg.MailboxID, arg.TagID)
	return err
}

const clearDomainTags = `-- name: ClearDomainTags :exec
DELETE FROM domain_tags WHERE domain_id = ?
`

func (q *Queries) ClearDomainTags(ctx context.Context, domainID int64) error {
	_, err := q.db.ExecContext(ctx, clearDomainTags, domainID)
	return err
}

const clearMailboxTags = `-- name: ClearMailboxTags :exec
DELETE FROM mailbox_tags WHERE mailbox_id = ?
`

func (q *Queries) ClearMailboxTags(ctx context.Context, mailboxID int64) error {
	_, err := q.db.ExecContext(ctx, clearMailboxTags, mailboxID)
	return err
}

const countTagUsage = `-- name: CountTagUsage :one
SELECT
    (SELECT COUNT(*) FROM domain_tags dt WHERE dt.tag_id = ?) +
    (SELECT COUNT(*) FROM mailbox_tags mt WHERE mt.tag_id = ?) AS total
`

type CountTagUsageParams struct {
	TagID   int64 `json:"tag_id"`
	TagID_2 int64 `json:"tag_id_2"`
}

func (q *Queries) CountTagUsage(ctx context.Context, arg CountTagUsageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTagUsage, arg.TagID, arg.TagID_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, color, created_at, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, color, created_at, updated_at
`

type CreateTagParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, color, created_at, updated_at FROM tags WHERE id = ? LIMIT 1
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, color, created_at, updated_at FROM tags WHERE name = ? LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagsForDomain = `-- name: GetTagsForDomain :many
SELECT t.id, t.name, t.color, t.created_at, t.updated_at FROM tags t
JOIN domain_tags dt ON dt.tag_id = t.id
WHERE dt.domain_id = ?
ORDER BY t.name ASC
`

func (q *Queries) GetTagsForDomain(ctx context.Context, domainID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForDomain, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForMailbox = `-- name: GetTagsForMailbox :many
SELECT t.id, t.name, t.color, t.created_at, t.updated_at FROM tags t
JOIN mailbox_tags mt ON mt.tag_id = t.id
WHERE mt.mailbox_id = ?
ORDER BY t.name ASC
`

func (q *Queries) GetTagsForMailbox(ctx context.Context, mailboxID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForMailbox, mailboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, color, created_at, updated_at FROM tags ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromDomain = `-- name: RemoveTagFromDomain :exec
DELETE FROM domain_tags WHERE domain_id = ? AND tag_id = ?
`

type RemoveTagFromDomainParams struct {
	DomainID int64 `json:"domain_id"`
	TagID    int64 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromDomain(ctx context.Context, arg RemoveTagFromDomainParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromDomain, arg.DomainID, arg.TagID)
	return err
}

const removeTagFromMailbox = `-- name: RemoveTagFromMailbox :exec
DELETE FROM mailbox_tags WHERE mailbox_id = ? AND tag_id = ?
`

type RemoveTagFromMailboxParams struct {
	MailboxID int64 `json:"mailbox_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromMailbox(ctx context.Context, arg RemoveTagFromMailboxParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromMailbox, arg.MailboxID, arg.TagID)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = ?, color = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, color, created_at, updated_at
`

type UpdateTagParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTag, arg.Name, arg.Color, arg.ID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
