// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package db

import (
	"context"
	"database/sql"
)

const countWebhooksByMailbox = `-- name: CountWebhooksByMailbox :one
SELECT COUNT(*) FROM webhooks WHERE mailbox_id = ?
`

func (q *Queries) CountWebhooksByMailbox(ctx context.Context, mailboxID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebhooksByMailbox, mailboxID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (
    mailbox_id, name, url, headers, hmac_secret,
    timeout_sec, max_retries, include_body, include_attachments, is_active,
    created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, mailbox_id, name, url, headers, hmac_secret, timeout_sec, max_retries, include_body, include_attachments, is_active, created_at, updated_at
`

type CreateWebhookParams struct {
	MailboxID          int64          `json:"mailbox_id"`
	Name               string         `json:"name"`
	Url                string         `json:"url"`
	Headers            sql.NullString `json:"headers"`
	HmacSecret         sql.NullString `json:"hmac_secret"`
	TimeoutSec         int64          `json:"timeout_sec"`
	MaxRetries         int64          `json:"max_retries"`
	IncludeBody        int64          `json:"include_body"`
	IncludeAttachments int64          `json:"include_attachments"`
	IsActive           int64          `json:"is_active"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.MailboxID,
		arg.Name,
		arg.Url,
		arg.Headers,
		arg.HmacSecret,
		arg.TimeoutSec,
		arg.MaxRetries,
		arg.IncludeBody,
		arg.IncludeAttachments,
		arg.IsActive,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.MailboxID,
		&i.Name,
		&i.Url,
		&i.Headers,
		&i.HmacSecret,
		&i.TimeoutSec,
		&i.MaxRetries,
		&i.IncludeBody,
		&i.IncludeAttachments,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = ?
`

func (q *Queries) DeleteWebhook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWebhook, id)
	return err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, mailbox_id, name, url, headers, hmac_secret, timeout_sec, max_retries, include_body, include_attachments, is_active, created_at, updated_at FROM webhooks WHERE id = ? LIMIT 1
`

func (q *Queries) GetWebhookByID(ctx context.Context, id int64) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.MailboxID,
		&i.Name,
		&i.Url,
		&i.Headers,
		&i.HmacSecret,
		&i.TimeoutSec,
		&i.MaxRetries,
		&i.IncludeBody,
		&i.IncludeAttachments,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWebhooksByMailbox = `-- name: ListActiveWebhooksByMailbox :many
SELECT id, mailbox_id, name, url, headers, hmac_secret, timeout_sec, max_retries, include_body, include_attachments, is_active, created_at, updated_at FROM webhooks WHERE mailbox_id = ? AND is_active = 1 ORDER BY created_at DESC
`

func (q *Queries) ListActiveWebhooksByMailbox(ctx context.Context, mailboxID int64) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWebhooksByMailbox, mailboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.MailboxID,
			&i.Name,
			&i.Url,
			&i.Headers,
			&i.HmacSecret,
			&i.TimeoutSec,
			&i.MaxRetries,
			&i.IncludeBody,
			&i.IncludeAttachments,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByMailbox = `-- name: ListWebhooksByMailbox :many
SELECT id, mailbox_id, name, url, headers, hmac_secret, timeout_sec, max_retries, include_body, include_attachments, is_active, created_at, updated_at FROM webhooks WHERE mailbox_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListWebhooksByMailbox(ctx context.Context, mailboxID int64) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooksByMailbox, mailboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.MailboxID,
			&i.Name,
			&i.Url,
			&i.Headers,
			&i.HmacSecret,
			&i.TimeoutSec,
			&i.MaxRetries,
			&i.IncludeBody,
			&i.IncludeAttachments,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks
SET name = ?, url = ?, headers = ?, hmac_secret = ?,
    timeout_sec = ?, max_retries = ?, include_body = ?, include_attachments = ?,
    is_active = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, mailbox_id, name, url, headers, hmac_secret, timeout_sec, max_retries, include_body, include_attachments, is_active, created_at, updated_at
`

type UpdateWebhookParams struct {
	Name               string         `json:"name"`
	Url                string         `json:"url"`
	Headers            sql.NullString `json:"headers"`
	HmacSecret         sql.NullString `json:"hmac_secret"`
	TimeoutSec         int64          `json:"timeout_sec"`
	MaxRetries         int64          `json:"max_retries"`
	IncludeBody        int64          `json:"include_body"`
	IncludeAttachments int64          `json:"include_attachments"`
	IsActive           int64          `json:"is_active"`
	ID                 int64          `json:"id"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, updateWebhook,
		arg.Name,
		arg.Url,
		arg.Headers,
		arg.HmacSecret,
		arg.TimeoutSec,
		arg.MaxRetries,
		arg.IncludeBody,
		arg.IncludeAttachments,
		arg.IsActive,
		arg.ID,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.MailboxID,
		&i.Name,
		&i.Url,
		&i.Headers,
		&i.HmacSecret,
		&i.TimeoutSec,
		&i.MaxRetries,
		&i.IncludeBody,
		&i.IncludeAttachments,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
