// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook_rules.sql

package db

import (
	"context"
	"database/sql"
)

const createWebhookRule = `-- name: CreateWebhookRule :one
INSERT INTO webhook_rules (webhook_id, rule_group, field, operator, value, header_name, created_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, webhook_id, rule_group, field, operator, value, header_name, created_at
`

type CreateWebhookRuleParams struct {
	WebhookID  int64          `json:"webhook_id"`
	RuleGroup  int64          `json:"rule_group"`
	Field      string         `json:"field"`
	Operator   string         `json:"operator"`
	Value      string         `json:"value"`
	HeaderName sql.NullString `json:"header_name"`
}

func (q *Queries) CreateWebhookRule(ctx context.Context, arg CreateWebhookRuleParams) (WebhookRule, error) {
	row := q.db.QueryRowContext(ctx, createWebhookRule,
		arg.WebhookID,
		arg.RuleGroup,
		arg.Field,
		arg.Operator,
		arg.Value,
		arg.HeaderName,
	)
	var i WebhookRule
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.RuleGroup,
		&i.Field,
		&i.Operator,
		&i.Value,
		&i.HeaderName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRulesByWebhook = `-- name: DeleteRulesByWebhook :exec
DELETE FROM webhook_rules WHERE webhook_id = ?
`

func (q *Queries) DeleteRulesByWebhook(ctx context.Context, webhookID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRulesByWebhook, webhookID)
	return err
}

const deleteWebhookRule = `-- name: DeleteWebhookRule :exec
DELETE FROM webhook_rules WHERE id = ?
`

func (q *Queries) DeleteWebhookRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWebhookRule, id)
	return err
}

const getWebhookRuleByID = `-- name: GetWebhookRuleByID :one
SELECT id, webhook_id, rule_group, field, operator, value, header_name, created_at FROM webhook_rules WHERE id = ? LIMIT 1
`

func (q *Queries) GetWebhookRuleByID(ctx context.Context, id int64) (WebhookRule, error) {
	row := q.db.QueryRowContext(ctx, getWebhookRuleByID, id)
	var i WebhookRule
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.RuleGroup,
		&i.Field,
		&i.Operator,
		&i.Value,
		&i.HeaderName,
		&i.CreatedAt,
	)
	return i, err
}

const listRulesByWebhook = `-- name: ListRulesByWebhook :many
SELECT id, webhook_id, rule_group, field, operator, value, header_name, created_at FROM webhook_rules WHERE webhook_id = ? ORDER BY rule_group, id
`

func (q *Queries) ListRulesByWebhook(ctx context.Context, webhookID int64) ([]WebhookRule, error) {
	rows, err := q.db.QueryContext(ctx, listRulesByWebhook, webhookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookRule{}
	for rows.Next() {
		var i WebhookRule
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.RuleGroup,
			&i.Field,
			&i.Operator,
			&i.Value,
			&i.HeaderName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
